language: node_js
sudo: false
node_js:
  - 0.10
script: karma start --no-auto-watch -–single-run 
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g bower 
  - npm install
  - bower install
after_success:
  - coveralls